// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz4zxuTaZyMe-gMC3ezp3Q7i7UaEKueqs',
    appId: '1:624617651104:web:ded67b330b52a81e5742c5',
    messagingSenderId: '624617651104',
    projectId: 'campus-compas-soen6751',
    authDomain: 'campus-compas-soen6751.firebaseapp.com',
    storageBucket: 'campus-compas-soen6751.firebasestorage.app',
    measurementId: 'G-9SQJ4VMM7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR2TdSpAqD95naLCKRGKJCrccsYnUjuMA',
    appId: '1:624617651104:android:9d6c820a8c4076855742c5',
    messagingSenderId: '624617651104',
    projectId: 'campus-compas-soen6751',
    storageBucket: 'campus-compas-soen6751.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcllcNPrgvYzF9RhdNcSvqXwrDJEH0pWo',
    appId: '1:624617651104:ios:05922ba689b0f9ed5742c5',
    messagingSenderId: '624617651104',
    projectId: 'campus-compas-soen6751',
    storageBucket: 'campus-compas-soen6751.firebasestorage.app',
    iosBundleId: 'com.example.campusCompass',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcllcNPrgvYzF9RhdNcSvqXwrDJEH0pWo',
    appId: '1:624617651104:ios:b32fc8b021f5ff4e5742c5',
    messagingSenderId: '624617651104',
    projectId: 'campus-compas-soen6751',
    storageBucket: 'campus-compas-soen6751.firebasestorage.app',
    iosBundleId: 'com.hcigroup6.campusCompass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz4zxuTaZyMe-gMC3ezp3Q7i7UaEKueqs',
    appId: '1:624617651104:web:cb2cffa8856fd3b55742c5',
    messagingSenderId: '624617651104',
    projectId: 'campus-compas-soen6751',
    authDomain: 'campus-compas-soen6751.firebaseapp.com',
    storageBucket: 'campus-compas-soen6751.firebasestorage.app',
    measurementId: 'G-KF85N117T2',
  );

}