// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz4zxuTaZyMe-gMC3ezp3Q7i7UaEKueqs',
    appId: '1:624617651104:web:ded67b330b52a81e5742c5',
    messagingSenderId: '624617651104',
    projectId: 'campus-compas-soen6751',
    authDomain: 'campus-compas-soen6751.firebaseapp.com',
    storageBucket: 'campus-compas-soen6751.firebasestorage.app',
    measurementId: 'G-9SQJ4VMM7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR2TdSpAqD95naLCKRGKJCrccsYnUjuMA',
    appId: '1:624617651104:android:388353a43245b94e5742c5',
    messagingSenderId: '624617651104',
    projectId: 'campus-compas-soen6751',
    storageBucket: 'campus-compas-soen6751.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcllcNPrgvYzF9RhdNcSvqXwrDJEH0pWo',
    appId: '1:624617651104:ios:a00fdd6ea7d2bc255742c5',
    messagingSenderId: '624617651104',
    projectId: 'campus-compas-soen6751',
    storageBucket: 'campus-compas-soen6751.firebasestorage.app',
    iosBundleId: 'com.farzadyounespour.campuscompass',
  );

}